[build]
  # Build command for the monorepo (builds web app)
  command = "cd apps/web && npm install && npm run build"
  # Publish directory (Next.js static export output)
  publish = "apps/web/out"

[build.environment]
  # Node.js version
  NODE_VERSION = "18"
  # Use npm instead of pnpm for better compatibility
  NPM_FLAGS = "--legacy-peer-deps"
  # Force npm to be used instead of pnpm
  NPM_CONFIG_PACKAGE_MANAGER = "npm"
  # Disable pnpm completely
  PNPM_HOME = ""
  # Force npm installation
  NPM_CONFIG_PREFER_NPM = "true"
  # Disable Next.js plugin detection
  NETLIFY_NEXT_PLUGIN_SKIP = "true"
  # Force static site mode
  NETLIFY_USE_YARN = "false"

# Handle static routing for Next.js static export
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Alternative deployment providers configuration
# For Vercel, add this to vercel.json:
# {
#   "rewrites": [
#     { "source": "/(.*)", "destination": "/index.html" }
#   ]
# }
# 
# For GitHub Pages, add this to .github/workflows/deploy.yml:
# - name: Deploy to GitHub Pages
#   uses: peaceiris/actions-gh-pages@v3
#   with:
#     github_token: ${{ secrets.GITHUB_TOKEN }}
#     publish_dir: ./apps/web/out

# Headers for security and performance
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"

# Cache static assets
[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Cache public assets
[[headers]]
  for = "/favicon*"
  [headers.values]
    Cache-Control = "public, max-age=86400"

[[headers]]
  for = "/*.svg"
  [headers.values]
    Cache-Control = "public, max-age=86400"


